# Generated by Django 3.0.7 on 2020-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='test', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
